name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint
